name: workflow-for-node-app
on:
   push:
      branches:
        - main
   workflow_dispatch:
jobs:
   job1-testing:
     runs-on: ubuntu-latest
     steps:
       - name: checkout the code
         uses: actions/checkout@v5
       - name: setup the Node environment
         uses: actions/setup-node@v5
         with:
           node-version: '22'
       - name: cache dependencies
         id: cache-deps
         uses: actions/cache@v4
         with:
            path: ./src/node_modules
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
               ${{ runner.os }}-node-
       - name: Install dependencies
         if: steps.cache-deps.outputs.cache-hit != 'true'
         run: npm ci
         working-directory: ./src
       - name: Linting...
         run: npm run lint
         working-directory: ./src
       - name: Run the tests
         run: npm test
         working-directory: ./src
       
   